### ISSUE TITLE
Game with unbounded number of turns lead to stack overflow

### ISSUE THREAD

**Issue by sherpal** [kaesve/muzero#5]
I apologize if this is out of the scope of this project, but I wanted to raise the point anyway, and perhaps receive some input.

The game I like to build an AI for is not bounded in terms of length (both players can, if they want, move their pieces around forever, which would also be the case for chess). With the current implementation of the `_search` method of the alpha MCTS class, it seems that it can cause stack overflow with the recursive call in the `elif not self.Ssa[(s, a)].done:  ### EXPANSION` clause.

In my case, average game length for random games is about 75, so I simply added an if clause
```
if len(path) > 400:
  value = -400
```
I have no idea whatsoever whether it make sens, but there you go.

Do you have any better solution? (Of course the minimum would be that this 400 is configurable...) Note that my game state already know its turn number, but I don't think it's good to include it in the hash of the game state, because then there is zero chance to go back to the same configuration (except for the very few turns).

**Comment by joeryjoery** [comment]
Hi, no our implementation isn't meant to deal with edge cases like infinite horizon MDPs. I believe that the original paper included a "cut-off" for long MDPs to more swiftly gain data --- i.e., every x steps they send the current data from an episode to an asynchronous data storage and then simply continue with the episode. So in this way you can circumvent this.

As for the stack overflow, I believe you mean a recursion error? If a game is very long, the MCTS class keeps track of a very large tree of hashes for computation efficiency. You could try call `MCTS.refresh()` every x steps too? Simply returning a value of `-400` may prevent the agent from choosing good actions.

If this doesn't help, alternatively you could set a maximum length and then bootstrap using the value network (in pseudo-code):
```python
if len(path) > max_len:
    v, pi = self.network.predict(state)
    return v if self.game.n_players == 1 else -v
```

Note that chess isn't infinite horizon due to the threefold repetition rule (it's about ~8-9k steps on a normal board). 

Does this help?

**Comment by sherpal** [comment]
Hello,

Yes, that helped a lot. I understand now that setting negative weight to stop the recursion (sorry for the name Stack Overflow, I'm more familiar with the JVM) is a bad idea.
So I changed the rules of the game (typically if no piece dies for a certain amount of time, it's a draw) and now it seems that it's learning something.

Thanks again
